Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('django.contrib.auth.urls')),
    path('donation/', include('donation.urls', namespace='donation')),
    path('beneficiary/', include('beneficiary.urls', namespace='beneficiary')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

]
# Serving static files during developmen
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Serving files uploaded by a user during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path , reverse_lazy
from django.views.decorators.csrf import csrf_exempt


from . import views
from . import api

app_name = 'accounts'

urlpatterns = [


    path('signup', views.signup, name='signup'),

    path('', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    # path('signup', views.CharitySignup, name='CharitySignup'),
    path('CharityProfile', views.CharityProfileView, name='CharityProfileView'),
    path('CharityProfile/edit', views.CharityProfileEdit, name='CharityProfileEdit'),
    path('CharityDonation', views.CharityDonationView, name='CharityDonationView'),

    # path('DonorDonation', views.DonorDonationView, name='DonorDonation'),
    #
    # path('donorProfile', views.DonorProfileView, name='DonorProfileView'),
    # path('donorProfile/edit', views.DonorProfileEdit, name='DonorProfileEdit'),






    path('api/signup', api.signup_user, name='signup_user'),  #
    path('api/login', api.CustomObtainAuthToken.as_view(), name='apilogin'),  #
    path('api/donorprofileupdate/<int:id>', api.donor_profile_update_api, name='donorprofileedit'),  #
    path('api/userupdate/<int:id>', api.user_update, name='userupdate'),
    path('api/donorprofile/<int:id>', api.donor_profile_api, name='donorprofileapi'),  #
    path('api/userprofile/<int:id>', api.user_profile, name='userprofile'),  #
    path('api/donordonation/<int:id>', api.donor_donation_api, name='donordonation'), #




]

donation/urls.py
from django.urls import path
from . import views, CharityViews, DonorViews
from . import api
app_name = 'donation'

urlpatterns = [

    path('', views.ViewDonationlist, name='donation_list'),
    path('<int:id>', views.ViewDonationDetils, name='donation_detail'),

    path('reserve/<int:id>', CharityViews.ReserveDonation, name='ReserveDonation'),
    path('deleteCharity/<int:id>', CharityViews.DeleteDonationCharity, name='DeleteDonationCharity'),
    path('donationDonor/<int:id>', CharityViews.donor_donation_profile, name='donor_donation_profile'),

    # path('edit/<int:id>', DonorViews.EditDonationDonor, name='EditDonationDonor'),
    # path('deleteDonor/<int:id>', DonorViews.DeleteDonationDonor, name='DeleteDonationDonor'),
    # path('add/', DonorViews.AddDonationDonor, name='AddDonationDonor'),

    path('map/<int:id>', views.mapDonation, name='map'),


    path('api/add', api.donation_add_api, name='donation_add'),
    path('api/update/<int:id>', api.donation_update_api, name='donation_update'),
    path('api/<int:id>', api.donation_details_api, name='donation_details'),
    path('api/delete/<int:id>', api.donation_delete_api, name='donation_delete'),
]

donation/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
from accounts.models import CharityProfile, DonorProfile

# Create your models here.

Packing_Type = (
    ('Packed', 'Packed'),
    ('Not Packed', 'Not Packed'),
)

Deliver_Type = (
    ('Delivery', 'Delivery'),
    ('No Delivery', 'No Delivery'),
)


class Donation(models.Model):
    donor = models.ForeignKey(DonorProfile, on_delete=models.CASCADE, blank=True, null=True)
    charity = models.ForeignKey(CharityProfile, on_delete=models.CASCADE, blank=True, null=True)
    Name = models.CharField(max_length=20, )
    Slug = models.SlugField(blank=True, null=True)
    description = models.TextField()
    Packing_Type = models.CharField(max_length=15, choices=Packing_Type)
    Deliver_Type = models.CharField(max_length=15, choices=Deliver_Type)
    Donate_Date = models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)
    Expiry_Date = models.DateTimeField()
    Available = models.BooleanField(default=True)

    lang = models.FloatField(max_length=15, null=True)
    lat = models.FloatField(max_length=15, null=True)

    def save(self, *args, **kwargs):
        if not self.Slug:
            self.Slug = slugify(self.Name)
        super(Donation, self).save(*args, **kwargs)

    @property
    def __str__(self):
        self.expiry_date_delete
        return self.Name

    @property
    def expiry_date_delete(self):
        if self.Expiry_Date.date() <= datetime.datetime.now().date():
            self.delete()

donation/forms.py
from django import forms
from .models import Donation


class DonationForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = '__all__'
        exclude = ('Slug' ,'donor','charity')

donation/views.py
from .models import Donation
from django.shortcuts import render

from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def ViewDonationlist(request):
    donation_list = Donation.objects.filter(Available=True)

    context = {
        'donations': donation_list,
    }
    return render(request, 'donation/donation_list.html', context)

@login_required
def ViewDonationDetils(request, id):
    donation_detail = Donation.objects.get(id=id)
    context = {
        'donation': donation_detail,
    }
    return render(request, 'donation/donation_detail.html', context)


def mapDonation(request, id):
    donationPlace = Donation.objects.get(id=id)
    return render(request, 'maps/map.html', {'card': donationPlace})

donation/templates/donation/AddDonation.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block add %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="" method="post">
    {% csrf_token %}
{% bootstrap_form form %}
    <hr>
    <button type="submit">save</button>
</form>
</body>
</html>
{% endblock add %}

donation/templates/donation/DonorDonationProfile.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}




    <div class="container">
  <div class="row">
    <div class="col-sm-2">

    </div>
    <div class="col-sm-10">
        <br>
        <br>
                <h3 class="card-title">{{ donor.user.first_name }} {{ donor.user.last_name }}</h3>
                <table style="width:100%">
                    <tr>
                        <th>Email :</th>

                        <th> {{ donor.user.email }}</th>
                    </tr>
                    <tr>
                        <th>Phone number :</th>

                        <th>{{ donor.Donor_Phone_Number }}</th>
                    </tr>
                    <tr>
                        <th>Address :</th>

                        <th> {{ donor.address }} </th>
                    </tr>
                    <tr>
                        <th>User name :</th>

                        <th> {{ donor.user.username }} </th>
                    </tr>
                </table>
                <br>
                <br>
                <p class="text-center col-8">
                    <a class="form-control text-decoration-none fw-bolder fs-5" style="color: cornflowerblue"
                       href="{% url 'accounts:CharityDonationView' %}"> Return To My Donation </a>
                </p>
            </div>
    <div class="col-sm-2">

    </div>
  </div>
</div>

{% endblock content %}

donation/templates/donation/donation_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

    <br>
    <br>
    <br>
    <div>
        <div class="col-sm-12 ">
            <div class="row ">
                <div class="col-4">
                    <br>
                    {% block map %}
                        {% include 'maps/map.html' with lat=donation.lat lang=donation.lang %}
                    {% endblock map %}

                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h3 class="card-title">{{ donation.Name }}</h3>
                        <table style="width:100%">
                            <tr>
                                <th>Donor Profile :</th>

                                <th>{{ donation.donor }}</th>
                            </tr>
                            <tr>
                                <th>Expiry Date :</th>

                                <th>{{ donation.Expiry_Date }}</th>
                            </tr>
                            <tr>
                                <th>Packing Type :</th>

                                <th>{{ donation.Packing_Type }}</th>
                            </tr>
                            <tr>
                                <th>Deliver Type :</th>

                                <th>{{ donation.Deliver_Type }} </th>
                            </tr>
                        </table>
                        <p>
                        <div class="fw-bolder">Description :</div>
                        <div>{{ donation.description }}</div>
                        </p>
                        <br>
                        <p class="text-center">
                            <a class="form-control text-decoration-none fw-bolder fs-5" style="color: cornflowerblue"
                               href="{% url 'donation:donor_donation_profile' donation.id %}"> Donor Profile </a>
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock content %}

donation/templates/donation/donation_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

    <br>
    <div class="container col-md-6">
        <p class="card border-dark text-center fw-bolder fs-2" style="color: cornflowerblue ">All Donations</p>
    </div>
    <br>
    <div class="container col-md-6">
        {% for donation in donations %}
            <div class="card border-dark ">
                <div class="card-header text-center fw-bold fs-5 ">
                    <a class="text-decoration-none" style="color: cornflowerblue"
                       href="{% url 'donation:donation_detail' donation.id %}">{{ donation.Name }}</a>
                </div>
                <div class="card-body">
                    <h6 class="card-title text-center fs-6 "><a>{{ donation.description }}</a></h6>
                    <div class="card-title text-end fw-light fs-6">
                        <a>Expiry Date : {{ donation.Expiry_Date }}</a>
                    </div>
                    <p class="text-center">
                        <a class="form-control text-decoration-none fw-bolder fs-5" style="color: cornflowerblue"
                           href="{% url 'donation:ReserveDonation' donation.id %}"> Reserve </a>
                    </p>

                </div>
            </div>
            <br>
        {% endfor %}

    </div>





{% endblock content %}