Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('django.contrib.auth.urls')),
    path('donation/', include('donation.urls', namespace='donation')),
    path('beneficiary/', include('beneficiary.urls', namespace='beneficiary')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

]
# Serving static files during developmen
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Serving files uploaded by a user during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beneficiary/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'beneficiary'

urlpatterns = [
    path('', views.all_beneficiary, name='bene_list'),
    path('<int:id>', views.beneficiary_detail, name='bene_detail'),
    path('add', views.add_beneficiary, name='add_beneficiary'),
    path('edit/<int:id>', views.edit_beneficiary, name='edit_beneficiary'),
    path('delete/<int:id>', views.delete_beneficiary, name='delete_beneficiary'),
]

beneficiary/models.py
from django.db import models
from django.utils.text import slugify
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
from accounts.models import CharityProfile


class Beneficiary(models.Model):
    user = models.ForeignKey(CharityProfile, on_delete=models.CASCADE ,null=True)
    name = models.CharField(max_length=25)
    phone_number = PhoneNumberField(blank=True)
    family_memebers_numbers = models.IntegerField(default=1)
    address = models.CharField(max_length=50)
    salary = models.IntegerField(default=0)


    def save(self, *args, **kwargs):
        super(Beneficiary, self).save(*args, **kwargs)


    def __str__(self):
        return self.name

beneficiary/forms.py
from django import forms
from .models import Beneficiary


class bene_form(forms.ModelForm):
    class Meta:
        model = Beneficiary
        fields= '__all__'
        exclude = ('Slug', 'user')

beneficiary/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Beneficiary
from .forms import bene_form
from accounts.models import CharityProfile
from django.contrib.auth.decorators import login_required


@login_required
def all_beneficiary(request):
    charity = get_object_or_404(CharityProfile, user=request.user)
    bene_list = Beneficiary.objects.filter(user_id=charity.id)
    ben = bene_form()
    if request.method == 'POST':
        add_beneficiary(request)
    context = {'bene_list': bene_list,
               'ben': ben
               }
    return render(request, 'bene_list.html', context)


@login_required
def beneficiary_detail(request, id):
    bene_detail = Beneficiary.objects.get(id=id)
    context = {
        'bene_detail': bene_detail,

    }
    return render(request, 'bene_detail.html', context)


@login_required
def add_beneficiary(request):
    charity = get_object_or_404(CharityProfile, user=request.user)

    if request.method == 'POST':
        ben = bene_form(request.POST, request.FILES)
        if ben.is_valid():
            ben = ben.save(commit=False)
            ben.user = charity
            ben.save()
            return redirect('beneficiary:add_beneficiary')
    else:
        ben = bene_form()
    context = {
        'ben': ben,

    }
    return render(request, 'add_bene.html', context)


@login_required
def edit_beneficiary(request, id):
    bene = get_object_or_404(Beneficiary, id=id)
    if request.method == 'POST':
        form = bene_form(request.POST, instance=bene)
        if form.is_valid():
            new_form = form
            new_form.save()
            return redirect('beneficiary:bene_list')
    else:
        form = bene_form(instance=bene)
    return render(request, 'edit_bene.html', {'form': form, 'bene': bene})


@login_required
def delete_beneficiary(request, id):
    get_object_or_404(Beneficiary, id=id).delete()
    return redirect('beneficiary:bene_list')

beneficiary/templates/add_bene.html
{% load static %}
{% load bootstrap4 %}
{% block add %}


    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
            integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
            integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
            crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">



    <br>
    <br>
    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Add New Beneficiary</h4>
                            <form action="" method="post">
                                {% csrf_token %}
                                {% bootstrap_form ben %}
                                {% buttons %}
                                    <br>
                                      <button class="form-control text-decoration-none fw-bolder fs-5" style="color: cornflowerblue" type="submit" href="{% url 'beneficiary:add_beneficiary' %}"  >Add</button>
                                {% endbuttons %}
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>


{% endblock add %}

beneficiary/templates/bene_detail.html
{% extends 'base.html' %}


{% load static %}
{% load bootstrap4 %}
{% block content %}
     <div class="container">
  <div class="row">
    <div class="col-sm-2">

    </div>
    <div class="col-sm-10">
        <br>
        <br>
                <h3 class="card-title">{{ bene_detail.name }}</h3>
                <table style="width:100%">
                    <tr>
                        <th>Phone number :</th>
                        <th>{{ bene_detail.phone_number }}</th>
                    </tr>
                    <tr>
                        <th>Address :</th>
                        <th> {{ bene_detail.address }} </th>
                    </tr>
                    <tr>
                        <th>Family Members :</th>
                        <th> {{ bene_detail.family_memebers_numbers }} </th>
                    </tr>
                    <tr>
                        <th>Monthly Income :</th>
                        <th> {{ bene_detail.salary }}</th>
                    </tr>
                </table>
                <br>
                <br>
                <p class="text-center col-8">
                    <a class="form-control text-decoration-none fw-bolder fs-5" style="color: cornflowerblue"
                       href="{% url 'beneficiary:bene_list' %}"> Return To Beneficiary </a>
                </p>
            </div>
    <div class="col-sm-2">

    </div>
  </div>
</div>


{% endblock content %}

beneficiary/templates/bene_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}






    <div class="accordion" id="accordionExample">
        <div class="accordion-item col-12">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button " type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    List of beneficiary
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show col-12" aria-labelledby="headingOne"
                 data-bs-parent="#accordionExample">
                <div class="accordion-body col-12">
                    <div class="container col-6">
                        <div class="col-12">
                            <table id="example4"
                                   class="table table-bordered table-hover col-9">
                                <thead>
                                <tr>
                                    <th style="text-align: center;color:black">Beneficiary</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for bene in bene_list %}
                                    <tr>
                                        <td>
                                            <div>
                                                <div class="row">
                                                    <div class="col-9">
                                                        <a class="text-decoration-none fw-bolder" style="color: cornflowerblue" href="{% url 'beneficiary:bene_detail' bene.id %}">{{ bene.name }}</a>
                                                    </div>
                                                    <div class="col-3">
                                                        <a class="nav-item btn btn btn-light"style="color: cornflowerblue"
                                                                href="{% url 'beneficiary:edit_beneficiary' bene.id %}">edit</a>
                                                        <a class="nav-item btn btn btn-light"style="color: cornflowerblue"
                                                                href="{% url 'beneficiary:delete_beneficiary' bene.id %}">delete</a>
                                                    </div>
                                                </div>
                                            </div>
                                            <br>

                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Add new beneficiary
                </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
                 data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <div class="container col-6">
                        <div class="col-xs-offset-6 ">
                            <br>
                            <br>
                            {% block add %}
                                {% include 'add_bene.html' with ben=ben %}
                            {% endblock add %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock content %}

beneficiary/templates/edit_bene.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

    <br>
    <br>
    <div class="container col-md-12">
        <div class="row">
            <div class="col-sm-3">
            </div>
            <div class="col-sm-6">
                <h4>Edit New Beneficiary</h4>
                <form action="" method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <br>
                        <button class="form-control text-decoration-none fw-bolder fs-5" style="color: cornflowerblue"
                                type="submit" href="{% url 'beneficiary:edit_beneficiary' bene.id %}">Edit Beneficiary
                            Profile
                        </button>
                    {% endbuttons %}
                </form>
            </div>
            <div class="col-sm-3"></div>
        </div>
        <br>
        <br>
        <br>
    </div>
    <br>
{% endblock content %}