Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('django.contrib.auth.urls')),
    path('donation/', include('donation.urls', namespace='donation')),
    path('beneficiary/', include('beneficiary.urls', namespace='beneficiary')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

]
# Serving static files during developmen
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Serving files uploaded by a user during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path , reverse_lazy
from django.views.decorators.csrf import csrf_exempt


from . import views
from . import api

app_name = 'accounts'

urlpatterns = [


    path('signup', views.signup, name='signup'),

    path('', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    # path('signup', views.CharitySignup, name='CharitySignup'),
    path('CharityProfile', views.CharityProfileView, name='CharityProfileView'),
    path('CharityProfile/edit', views.CharityProfileEdit, name='CharityProfileEdit'),
    path('CharityDonation', views.CharityDonationView, name='CharityDonationView'),

    # path('DonorDonation', views.DonorDonationView, name='DonorDonation'),
    #
    # path('donorProfile', views.DonorProfileView, name='DonorProfileView'),
    # path('donorProfile/edit', views.DonorProfileEdit, name='DonorProfileEdit'),






    path('api/signup', api.signup_user, name='signup_user'),  #
    path('api/login', api.CustomObtainAuthToken.as_view(), name='apilogin'),  #
    path('api/donorprofileupdate/<int:id>', api.donor_profile_update_api, name='donorprofileedit'),  #
    path('api/userupdate/<int:id>', api.user_update, name='userupdate'),
    path('api/donorprofile/<int:id>', api.donor_profile_api, name='donorprofileapi'),  #
    path('api/userprofile/<int:id>', api.user_profile, name='userprofile'),  #
    path('api/donordonation/<int:id>', api.donor_donation_api, name='donordonation'), #




]

donation/urls.py
from django.urls import path
from . import views, CharityViews, DonorViews
from . import api
app_name = 'donation'

urlpatterns = [

    path('', views.ViewDonationlist, name='donation_list'),
    path('<int:id>', views.ViewDonationDetils, name='donation_detail'),

    path('reserve/<int:id>', CharityViews.ReserveDonation, name='ReserveDonation'),
    path('deleteCharity/<int:id>', CharityViews.DeleteDonationCharity, name='DeleteDonationCharity'),
    path('donationDonor/<int:id>', CharityViews.donor_donation_profile, name='donor_donation_profile'),

    # path('edit/<int:id>', DonorViews.EditDonationDonor, name='EditDonationDonor'),
    # path('deleteDonor/<int:id>', DonorViews.DeleteDonationDonor, name='DeleteDonationDonor'),
    # path('add/', DonorViews.AddDonationDonor, name='AddDonationDonor'),

    path('map/<int:id>', views.mapDonation, name='map'),


    path('api/add', api.donation_add_api, name='donation_add'),
    path('api/update/<int:id>', api.donation_update_api, name='donation_update'),
    path('api/<int:id>', api.donation_details_api, name='donation_details'),
    path('api/delete/<int:id>', api.donation_delete_api, name='donation_delete'),
]

accounts/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

from rest_framework.authtoken.models import Token

def image_upload(instance,filename):
    imagename , extension = filename.split(".")
    return "license_image/%s.%s"%(instance.id,extension)


class CharityProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=25, null=True)
    Charity_Slug = models.SlugField(blank=True, null=True)
    Charity_Phone_Number = PhoneNumberField()
    address = models.CharField(max_length=30)
    license_image = models.ImageField(upload_to=image_upload, default='default.jpg')

    def save(self, *args, **kwargs):

        if not self.Charity_Slug:
            self.Charity_Slug = slugify(self.user)
        super(CharityProfile, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.user)


class DonorProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    Donor_Slug = models.SlugField(blank=True, null=True)

    Donar_Employment_Type = models.CharField(max_length=30)
    Donor_Phone_Number = PhoneNumberField()
    address = models.CharField(max_length=30)

    # location

    def save(self, *args, **kwargs):
        self.id = self.user.id
        if not self.Donor_Slug:
            self.Donor_Slug = slugify(self.user)
        super(DonorProfile, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import CharityProfile , DonorProfile


user_type = (
    ('Donor', 'Donor'),
    ('Charity', 'Charity'),
)



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'

        ]




class CharityUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields= fields = ['username','first_name','last_name','email']


class CharityProfileForm(forms.ModelForm):
    class Meta:
        model = CharityProfile
        fields = '__all__'
        exclude = ('Charity_Slug','user')



class DonorUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields= ['username','first_name','last_name','email']


class DonorProfileForm(forms.ModelForm):
    class Meta:
        model = DonorProfile
        fields = "__all__"

accounts/views.py
from django.contrib.auth import authenticate, login
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .forms import SignupForm, CharityUserForm, CharityProfileForm, DonorUserForm, DonorProfileForm
from .models import CharityProfile
from donation.models import Donation
from django.contrib.auth.decorators import login_required


# Create your views here.


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            CharityProfile.objects.create(user=user)
            login(request, user)
            return redirect('accounts:CharityProfileEdit')
        else:
            raise Http404("Poll does not exist")
    else:
        form = SignupForm()
    return render(request, 'Signup.html', {'form': form})


@login_required
def CharityProfileView(request):
    Charity_Profile = CharityProfile.objects.get(user=request.user)
    donation = Donation.objects.filter(charity_id=Charity_Profile.id)
    return render(request, 'charityprofile.html', {'profile': Charity_Profile, 'donation': donation})


@login_required
def CharityProfileEdit(request):
    Charity_Profile = CharityProfile.objects.get(user=request.user)

    if request.method == 'POST':
        userform = CharityUserForm(request.POST, instance=request.user)
        profileform = CharityProfileForm(request.POST, request.FILES, instance=Charity_Profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile = profileform.save(commit=False)
            myprofile.user = request.user
            myprofile.save()
            return redirect(reverse('accounts:CharityProfileView'))

    else:
        userform = CharityUserForm(instance=request.user)
        profileform = CharityProfileForm(instance=Charity_Profile)

    return render(request, 'registration/profile_edit.html',
                  {'userform': userform, 'profileform': profileform})


@login_required
def CharityDonationView(request):
    charity = get_object_or_404(CharityProfile, user=request.user)
    charityDonation = Donation.objects.filter(charity_id=charity.id)
    return render(request, 'CharityDonation.html', {'charity': charity, 'charityDonation': charityDonation})


# @login_required
# def DonorProfileView(request):
#     Donor_Profile = DonorProfile.objects.get(user=request.user)
#     return render(request, 'donorprofile.html', {'profile': Donor_Profile})
#
#
# def DonorProfileEdit(request):
#     Donor_Profile = DonorProfile.objects.get(user=request.user)
#
#     if request.method == 'POST':
#         userform = DonorUserForm(request.POST, instance=request.user)
#         profileform = DonorProfileForm(request.POST, request.FILES, instance=Donor_Profile)
#         if DonorUserForm.is_valid() and DonorProfileForm.is_valid():
#             DonorUserForm.save()
#             myprofile = DonorProfileForm.save(commit=False)
#             myprofile.user = request.user
#             myprofile.save()
#             return redirect(reverse('registration:profile'))
#
#     else:
#         userform = DonorUserForm(instance=request.user)
#         profileform = DonorProfileForm(instance=Donor_Profile)
#
#     return render(request, 'registration/profile_edit.html',
#                   {'userform': DonorUserForm, 'profileform': DonorProfileForm})
#
#
# def DonorDonationView(request):
#     donar = get_object_or_404(DonorProfile, user=request.user)
#     donar_Donation = Donation.objects.filter(donor_id=donar.id)
#
#     return render(request, 'donordonation.html', {'donar': donar, 'donar_Donation': donar_Donation, })

accounts/templates/CharityDonation.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

    <br>
    <div class="container col-md-6">
        <p class="card border-dark text-center fw-bolder fs-2" style="color: cornflowerblue ;text-shadow: deepskyblue">
            My
            Donations</p>
    </div>
    <br>
    <div class="container col-md-6">
        {% for donation in charityDonation %}
            <div class="card border-dark ">
                <div class="card-header text-center fw-bold fs-5 ">
                    <a class="text-decoration-none" style="color: cornflowerblue"
                       href="{% url 'donation:donation_detail' donation.id %}">{{ donation.Name }}</a>
                </div>
                <div class="card-body">
                    <h6 class="card-title text-center fs-6 "><a>{{ donation.description }}</a></h6>
                    <div class="card-title text-end fw-light fs-6">
                        <a>Expiry Date : {{ donation.Expiry_Date }}</a>
                    </div>
                    <p class="text-center">
                        <a class="form-control text-decoration-none fw-bolder fs-5" style="color: cornflowerblue"
                           href="{% url 'donation:DeleteDonationCharity'  donation.id %}"> Cancel Reserve </a>
                    </p>
                </div>
            </div>

            <br>
        {% endfor %}
    </div>






{% endblock content %}

accounts/templates/Signup.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
    <br>
    <br>
    <br>
    <div class="container col-md-12">
        <div class="row">
            <div class="col-sm-3">
            </div>
            <div class="col-sm-6">
            <h2>Sign up Form</h2>
            <form method="post" >
                {% csrf_token %}
                {% bootstrap_form form %}
                <br>
                <button type="submit" class="btn btn-primary">Sign up</button>
            </form>
            <br>
            <br>
            <br>
            <br>
            </div>
            <div class="col-sm-3"></div>
        </div>
        <br>
        <br>
        <br>
    </div>
{% endblock content %}

accounts/templates/charityprofile.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}




    <div>
        <div class="col-sm-12">
            <div class="row ">
                <div class="col-4 gmap_canvas" >
                    <br>
                    <img class="img-responsive " style="height: 400px ;width: 400px" src="{{ profile.license_image.url }} ">


                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <br>
                        <br>
                        <br>

                        <h3 class="card-title">{{ profile.name }}</h3>
                        <table style="width:100%">
                            <tr>
                                <th>Email :</th>

                                <th> {{ profile.user.email }}</th>
                            </tr>
                            <tr>
                                <th>Phone number :</th>

                                <th>{{ profile.Charity_Phone_Number }}</th>
                            </tr>
                            <tr>
                                <th>Address :</th>

                                <th> {{ profile.address }} </th>
                            </tr>
                            <tr>
                                <th>User name :</th>

                                <th> {{ profile.user.username }} </th>
                            </tr>
                        </table>
                        <br>
                        <p class="text-center col-md-8">
                            <a class="form-control text-decoration-none fw-bolder fs-5" style="color: cornflowerblue"
                               href="{% url 'accounts:CharityProfileEdit' %}"> Edit Profile </a>
                        </p>
                        <br>
                        <p class="text-center col-md-8">
                            <a class="form-control text-decoration-none fw-bolder fs-5" style="color: cornflowerblue"
                               href="{% url 'accounts:password_change' %}"> Change Password </a>
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>
<br>
<br>

<br>

{% endblock content %}

accounts/templates/donordonation.html
{{ donar }}
<br>

{% for foo in donar_Donation %}
    {{ foo }} ## <a href="{% url 'donation:DeleteDonationDonor' foo.id %}"> delete </a>
    # <a href="{% url 'donation:EditDonationDonor' foo.id %}"> edit </a>
    <hr>
{% endfor %}

<a href="{% url 'donation:AddDonationDonor' %}"> AddDonationDonor </a>

accounts/templates/donorprofile.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-light" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

accounts/templates/mydonations.html
{#{{ mydonations }}#}


{{ x }}
<br>
{{ y }}