Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('django.contrib.auth.urls')),
    path('donation/', include('donation.urls', namespace='donation')),
    path('beneficiary/', include('beneficiary.urls', namespace='beneficiary')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

]
# Serving static files during developmen
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Serving files uploaded by a user during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path , reverse_lazy
from django.views.decorators.csrf import csrf_exempt


from . import views
from . import api

app_name = 'accounts'

urlpatterns = [


    path('signup', views.signup, name='signup'),

    path('', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    # path('signup', views.CharitySignup, name='CharitySignup'),
    path('CharityProfile', views.CharityProfileView, name='CharityProfileView'),
    path('CharityProfile/edit', views.CharityProfileEdit, name='CharityProfileEdit'),
    path('CharityDonation', views.CharityDonationView, name='CharityDonationView'),

    # path('DonorDonation', views.DonorDonationView, name='DonorDonation'),
    #
    # path('donorProfile', views.DonorProfileView, name='DonorProfileView'),
    # path('donorProfile/edit', views.DonorProfileEdit, name='DonorProfileEdit'),






    path('api/signup', api.signup_user, name='signup_user'),  #
    path('api/login', api.CustomObtainAuthToken.as_view(), name='apilogin'),  #
    path('api/donorprofileupdate/<int:id>', api.donor_profile_update_api, name='donorprofileedit'),  #
    path('api/userupdate/<int:id>', api.user_update, name='userupdate'),
    path('api/donorprofile/<int:id>', api.donor_profile_api, name='donorprofileapi'),  #
    path('api/userprofile/<int:id>', api.user_profile, name='userprofile'),  #
    path('api/donordonation/<int:id>', api.donor_donation_api, name='donordonation'), #




]

beneficiary/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'beneficiary'

urlpatterns = [
    path('', views.all_beneficiary, name='bene_list'),
    path('<int:id>', views.beneficiary_detail, name='bene_detail'),
    path('add', views.add_beneficiary, name='add_beneficiary'),
    path('edit/<int:id>', views.edit_beneficiary, name='edit_beneficiary'),
    path('delete/<int:id>', views.delete_beneficiary, name='delete_beneficiary'),
]

donation/urls.py
from django.urls import path
from . import views, CharityViews, DonorViews
from . import api
app_name = 'donation'

urlpatterns = [

    path('', views.ViewDonationlist, name='donation_list'),
    path('<int:id>', views.ViewDonationDetils, name='donation_detail'),

    path('reserve/<int:id>', CharityViews.ReserveDonation, name='ReserveDonation'),
    path('deleteCharity/<int:id>', CharityViews.DeleteDonationCharity, name='DeleteDonationCharity'),
    path('donationDonor/<int:id>', CharityViews.donor_donation_profile, name='donor_donation_profile'),

    # path('edit/<int:id>', DonorViews.EditDonationDonor, name='EditDonationDonor'),
    # path('deleteDonor/<int:id>', DonorViews.DeleteDonationDonor, name='DeleteDonationDonor'),
    # path('add/', DonorViews.AddDonationDonor, name='AddDonationDonor'),

    path('map/<int:id>', views.mapDonation, name='map'),


    path('api/add', api.donation_add_api, name='donation_add'),
    path('api/update/<int:id>', api.donation_update_api, name='donation_update'),
    path('api/<int:id>', api.donation_details_api, name='donation_details'),
    path('api/delete/<int:id>', api.donation_delete_api, name='donation_delete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .fa {
            padding: 8px;
            font-size: 20px;
            width: 35px;
            text-align: center;
            text-decoration: none;
            margin: 5px 8px;
            border-radius: 50%;
        }

        .fa:hover {
            opacity: 0.7;
        }

        .fa-facebook {
            background: #3B5998;
            color: white;
        }

        .fa-twitter {
            background: #55ACEE;
            color: white;
        }


        .fa-instagram {
            background: #125688;
            color: white;
        }


        .fa-flickr {
            background: #f40083;
            color: white;
        }


    </style>
</head>
<body style="overflow-x: hidden;">
<div class="row">
    {% include 'nav1.html' %}
</div>
<div class="container-fluid" style="min-height: 350px">
    {% block content %}

    {% endblock %}
</div>


<div class="row ">
    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <h6>About</h6>
                    <p class="text-justify">Happy Bite <i>OUR VISION  </i></p><p> it’s not right that
                        anyone cannot afford their own food. That’s why we are working towards a just,
                        compassionate future, where no one should have to use donations to get by.</p>
                    <p>We stand on the edge of a precipice, with a clear decision to make: either we accept
                        food banks as a ‘new normal’, or we work to create a more dignified, compassionate,
                        and just society where everyone has enough money for the essentials. </p>
                    <p>We seek to link charities and donors to provide the fewest rights which is the
                        food for the zero income class</p>
                </div>

                <div class="col-xs-6 col-md-3">


                </div>

                <div class="col-xs-6 col-md-3">
                    <h6>Developed using</h6>
                    <ul class="footer-links">
                        <li><a>Django</a></li>
                        <li><a>Django REST framework</a></li>
                        <li><a>SQLite</a></li>
                        <li><a>HTML CSS JS</a></li>
                        <li><a>Bootstrap4</a></li>
                    </ul>
                </div>
            </div>
            <hr>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <p class="copyright-text">Copyright &copy; 2021 All Rights Reserved by
                        <a href="https://www.facebook.com/mohand.azar1/">Mohanad Azar</a>.
                    </p>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12">
                    <ul >
                        <a href="https://www.facebook.com/mohand.azar1/" class="fa fa-facebook"></a>
                        <a href="https://twitter.com/Mohanad33616710" class="fa fa-twitter"></a>
                        <a href="https://www.instagram.com/azarmohanad/" class="fa fa-instagram"></a>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
</div>
<style>
    .site-footer {
        background-color: #26272b;
        padding: 45px 0 20px;
        font-size: 15px;
        line-height: 24px;
        color: #737373;
    }

    .site-footer hr {
        border-top-color: #bbb;
        opacity: 0.5
    }

    .site-footer hr.small {
        margin: 20px 0
    }

    .site-footer h6 {
        color: #fff;
        font-size: 16px;
        text-transform: uppercase;
        margin-top: 5px;
        letter-spacing: 2px
    }

    .site-footer a {
        color: #737373;
    }

    .site-footer a:hover {
        color: #3366cc;
        text-decoration: none;
    }

    .footer-links {
        padding-left: 0;
        list-style: none
    }

    .footer-links li {
        display: block
    }

    .footer-links a {
        color: #737373
    }

    .footer-links a:active, .footer-links a:focus, .footer-links a:hover {
        color: #3366cc;
        text-decoration: none;
    }

    .footer-links.inline li {
        display: inline-block
    }

    .site-footer .social-icons {
        text-align: right
    }

    .site-footer .social-icons a {
        width: 40px;
        height: 40px;
        line-height: 40px;
        margin-left: 6px;
        margin-right: 0;
        border-radius: 100%;
        background-color: #33353d
    }

    .copyright-text {
        margin: 0
    }

    @media (max-width: 991px) {
        .site-footer [class^=col-] {
            margin-bottom: 30px
        }
    }

    @media (max-width: 767px) {
        .site-footer {
            padding-bottom: 0
        }

        .site-footer .copyright-text, .site-footer .social-icons {
            text-align: center
        }
    }

    .social-icons {
        padding-left: 0;
        margin-bottom: 0;
        list-style: none
    }

    .social-icons li {
        display: inline-block;
        margin-bottom: 4px
    }

    .social-icons li.title {
        margin-right: 15px;
        text-transform: uppercase;
        color: #96a2b2;
        font-weight: 700;
        font-size: 13px
    }

    .social-icons a {
        background-color: #eceeef;
        color: #818a91;
        font-size: 16px;
        display: inline-block;
        line-height: 44px;
        width: 44px;
        height: 44px;
        text-align: center;
        margin-right: 8px;
        border-radius: 100%;
        -webkit-transition: all .2s linear;
        -o-transition: all .2s linear;
        transition: all .2s linear
    }

    .social-icons a:active, .social-icons a:focus, .social-icons a:hover {
        color: #fff;
        background-color: #29aafe
    }

    .social-icons.size-sm a {
        line-height: 34px;
        height: 34px;
        width: 34px;
        font-size: 14px
    }

    .social-icons a.facebook:hover {
        background-color: #3b5998;
        color: white;
    }

    .social-icons a.twitter:hover {
        background-color: #00aced
    }

    .social-icons a.linkedin:hover {
        background-color: #007bb6
    }

    .social-icons a.dribbble:hover {
        background-color: #ea4c89
    }

    @media (max-width: 767px) {
        .social-icons li.title {
            display: block;
            margin-right: 0;
            font-weight: 600
        }


    }

</style>

<meta charset="UTF-8">
<title>Happy Bite</title>

<meta charset="UTF-8">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
        integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">

</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}



{% endblock content %}

templates/nav1.html
{% load bootstrap4 %}


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand  fw-bolder fs-4" >Happy Bite</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:CharityProfileView' %}">Home</a>
                    </li>


                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'beneficiary:bene_list' %}">Beneficiary</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:CharityDonationView' %}">My Donation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'donation:donation_list' %}">Reserve Donation</a>
                        </li>

                        </ul>
                        </div>

                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="#"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"></a>
                        </li>
                        </ul>
                        </div>

                    {% endif %}

        {% if request.user.is_authenticated %}

            <a class="nav-item btn btn btn-light" href="{% url 'accounts:logout' %}">Logout</a>

        {% else %}

            <a class="nav-item btn btn btn-light" href="{% url 'accounts:login' %}">Login</a>

        {% endif %}

    </nav>